---
deployment:
  tasks:
    - export DEPLOYPATH=/home/fezadano5
    - /bin/cp -R * $DEPLOYPATH/
    - /bin/cp -R .htaccess $DEPLOYPATH/ 2>/dev/null || true
    - /bin/cp -R .env $DEPLOYPATH/ 2>/dev/null || true
